### **1. Importing Libraries**

In [27]:
import pandas as pd
from pathlib import Path

### **2. Define Project Paths**

In [28]:
#get project root
PROJECT_ROOT = Path().resolve().parent

In [29]:
#data directories
RAW_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

In [30]:
#file paths
CRITICAL_FILE = PROCESSED_DIR / "critical_escalation_table.csv"
CONTACT_FILE = RAW_DIR / "contact_details.xlsx"
MERGED_FILE = PROCESSED_DIR / "critical_contacts.csv"

### **3. Loading Data**

In [34]:
critical_df = pd.read_csv(CRITICAL_FILE)
contacts_df = pd.read_excel(CONTACT_FILE)

### **4. Merge Data on PRN and Name**

We would merge on the bases of the *PRN* and the *Name* cause they are the unique and same values in both the data

In [ ]:
merged_df = pd.merge(
    critical_df,
    contacts_df,
    on = ["PRN", "Name"],
    how = "left"
)

,PRN,Name,Lectures_Attended,Total_Lectures_Batch,Net_Attendance_Percentage,risk_category,performance_score,email,phone,whatsapp
0,201,Student 1,5,17,29.411765,Critical,0.000000,tanmayjain@gmail.com,9920519546,9920519546
1,203,Student 3,5,17,29.411765,Critical,0.000000,tanmayjain@gmail.com,9920519546,9920519546
2,204,Student 4,5,16,31.250000,Critical,0.034722,tanmayjain@gmail.com,9920519546,9920519546
3,206,Student 6,5,16,31.250000,Critical,0.034722,tanmayjain@gmail.com,9920519546,9920519546
4,207,Student 7,5,16,31.250000,Critical,0.034722,tanmayjain@gmail.com,9920519546,9920519546

### **5. Cleaning the merged_df**

In this we would drop the unnecessary columns and only keep the required : 
- *risk_category* and *performance_score* is unnecessary
- *PRN, Name, Lectures_Attended, Total_Lectures_Batch* and *Net_Attendance_Percentage* are required for the custom message
- *email, phone* and *whatsapp* are for the contacts

In [ ]:
columns_to_drop = ["risk_category","performance_score"]
merged_df = merged_df.drop(
    columns = [
        col for col in columns_to_drop 
            if col in merged_df.columns
    ]
)

,PRN,Name,Lectures_Attended,Total_Lectures_Batch,Net_Attendance_Percentage,email,phone,whatsapp
0,201,Student 1,5,17,29.411765,tanmayjain@gmail.com,9920519546,9920519546
1,203,Student 3,5,17,29.411765,tanmayjain@gmail.com,9920519546,9920519546
2,204,Student 4,5,16,31.250000,tanmayjain@gmail.com,9920519546,9920519546
3,206,Student 6,5,16,31.250000,tanmayjain@gmail.com,9920519546,9920519546
4,207,Student 7,5,16,31.250000,tanmayjain@gmail.com,9920519546,9920519546